"""Drafts built on a finished run: a research proposal, or a review manuscript.

A proposal argues that a gap exists, matters, and can be closed, and says how. A review manuscript reports
the run itself as a literature review (methods, study selection, findings, discussion). Both are written
from the run's own evidence, in three steps:

1. Plan. The Draft Planner agent works over the run like the Follow-up agent does (claims, map items,
   papers, results tables, research versus burden). It counts what the argument needs, so every number the
   draft uses is a verified claim, and returns an outline: for each section, its points and the claims and
   papers behind them.
2. Write. Each section is written in its own call, from a fixed evidence pack (claims, paper records,
   computed tables) plus the sections already written. Short outputs never get cut off, and the shared start
   of every call is served from the provider's prompt cache.
3. Check. The draft goes through the report's checks: untraced "n of N" figures are measured, corrected or
   removed by the Number Check agent, citations to papers outside the run are removed, claim citations must
   be supported and match their numbers. References and the evidence table are generated by code.

Statements about the literature are evidence and are checked. Aims, methods, outcomes and the workplan of a
proposal are the applicant's plan, not findings, and the draft says so. A review manuscript states that
screening and extraction were automated, because a reader must know that.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone

from research_agent.agents.base import Agent
from research_agent.agents.followup import (ITEM_TOOL, OVERVIEW_TOOL, READ_TOOL, _counted, _ensure_schema,
                                            audit_answer, get_item)
from research_agent.agents.report import _CITE_CLAIM, _clean_author, _cited_ids, get_brief, run_facts
from research_agent.config import settings
from research_agent.db import connect
from research_agent.runstate import RunContext
from research_agent.tools.base import STR, STRS, Tool, obj
from research_agent.tools.burden import BURDEN_TOOL
from research_agent.tools.citations import CITATION_INFO_TOOL
from research_agent.tools.claims import PREDICATE_DOC, TEST_TOOL, propose_claim, verify_claims
from research_agent.tools.extraction import ANALYSIS_TOOLS, _rows
from research_agent.tools.recheck import RECHECK_TOOL
from research_agent.tools.results import RESULT_TOOLS

# ---------------------------------------------------------------- what each kind of draft contains
# (key, heading, role, guidance, words). role: evidence = statements about the literature, checked;
# plan = the applicant's proposal; record = how the review was done, from facts computed by code.
PROPOSAL = [
    ("background", "Background and rationale", "evidence",
     "The problem and why it matters for health (burden, decisions that depend on it), what the field has "
     "achieved so far and which approaches are established. Build towards the gap; end on what is missing.", 650),
    ("gap", "The evidence gap", "evidence",
     "State the gap precisely and prove it with the counts in the outline (how few studies do X, in which "
     "settings, relative to burden). Explain why it has persisted and what it costs: which conclusions or "
     "decisions are unreliable while it stays open. Say where the evidence for the gap itself is thin.", 550),
    ("aims", "Aims and objectives", "plan",
     "One overall aim, then 3 to 4 specific, measurable objectives, each tied to part of the gap. A short "
     "numbered list is right here, each item a full sentence. Add the research questions or hypotheses.", 300),
    ("methods", "Proposed methods", "plan",
     "Study design; data sources (prefer ones the analysed papers used, and cite them); the modelling "
     "approach and the baselines it must beat; the validation design, chosen to fix the weaknesses the "
     "evidence shows; the analysis plan and how success will be judged. Use ### subheadings.", 900),
    ("outcomes", "Expected outcomes and significance", "plan",
     "What the work will deliver, who will use it, and how it changes practice or the evidence base. Tie each "
     "outcome back to the gap. No promised numbers.", 350),
    ("risks", "Risks, limitations and mitigation", "plan",
     "The main risks (data access, data quality, transferability, the limits of the evidence behind the gap) "
     "and how each will be handled. A short list is acceptable.", 350),
    ("ethics", "Ethics and data management", "plan",
     "Approvals needed, data protection, data sharing and code availability. Keep it brief.", 180),
    ("timeline", "Workplan and timeline", "plan",
     "Work packages with their outputs and months, as a Markdown table (work package, activities, months, "
     "deliverable), then one short paragraph. Leave durations the applicant must set as placeholders.", 250),
]
PROPOSAL_LAST = ("summary", "Summary", "evidence",
                 "A self-contained summary of the whole proposal in two or three paragraphs: the problem, the gap "
                 "with its key count, the aims, the approach and the expected outcome.", 300)

REVIEW = [
    ("introduction", "Introduction", "evidence",
     "The health problem, why this question matters, what earlier work and reviews leave open, and the "
     "objective of this review stated plainly in the last paragraph.", 600),
    ("methods", "Methods", "record",
     "How the review was done, only from the review record in the pack: sources and dates, search strategy, "
     "eligibility, screening, data items (what was extracted and that every value needed a verified quote), "
     "how results and associations were extracted, and the synthesis (counts computed by code, within-paper "
     "method comparisons, contradictions). Use ### subheadings: Sources and search; Eligibility and "
     "screening; Data extraction; Synthesis. Past tense. Never claim a step that the record does not show.", 650),
    ("results_selection", "Results: study selection and characteristics", "evidence",
     "Study selection with the PRISMA counts from the pack (refer to Figure 1 if figures_and_tables lists it), then the characteristics of "
     "the included studies: years, sources, settings, data types, methods and validation practice, with "
     "counts from supported claims.", 600),
    ("results_synthesis", "Results: synthesis of findings", "evidence",
     "The findings, organised by theme with ### subheadings: what approaches perform well (within-paper "
     "comparisons only), which drivers are reported and where studies disagree, and the gaps. Refer to the "
     "numbered tables in figures_and_tables where they apply. Report, do not yet interpret at length.", 900),
    ("discussion", "Discussion", "evidence",
     "Principal findings; what they mean for validity, transferability and use in decisions; how they relate "
     "to the wider literature; strengths and limitations of this review (include that screening and "
     "extraction were automated, that some papers were read from abstracts only, and the corpora covered); "
     "implications for research and practice. Use ### subheadings.", 900),
    ("conclusions", "Conclusions", "evidence",
     "One or two paragraphs: the answer to the review question and the most important next step.", 200),
]
REVIEW_LAST = ("abstract", "Abstract", "evidence",
               "A structured abstract with bold run-in labels: **Background.** **Methods.** **Results.** "
               "**Conclusions.** One short paragraph each, with the key counts.", 300)

KINDS = {"proposal": ("Research proposal", PROPOSAL, PROPOSAL_LAST),
         "review": ("Review manuscript", REVIEW, REVIEW_LAST)}

AUTOMATION_NOTE = ("*Note on automation.* Searching, title and abstract screening, and data extraction were "
                   "carried out by language-model agents rather than by two independent human reviewers. Every "
                   "extracted value had to be supported by a passage copied from the paper, and code checked each "
                   "passage against the paper's text before the value was used; counts and comparisons were "
                   "computed by code from those records. Readers should treat screening decisions as a single "
                   "automated pass that has not been duplicated or adjudicated by people.")


# ---------------------------------------------------------------- directions a draft can argue for
def directions(ctx) -> list[dict]:
    """Candidate gaps and directions from the run: map gaps, novel combinations and designs, or the gaps the
    Gap agent reported in an ordinary run."""
    notes = ctx.notes()
    out = []
    m = (notes.get("map") or {}).get("map") or {}
    for it in m.get("gaps", []):
        share = f" ({it['n']} of {it['N']} papers)" if it.get("N") else ""
        out.append({"id": it["id"], "kind": "gap", "label": f"{it['label']}{share}"})
    for it in m.get("novelty", []):
        out.append({"id": it["id"], "kind": "untried combination", "label": f"{it['a']['label']} + {it['b']['label']}"})
    for d in (notes.get("design") or {}).get("designs", []):
        out.append({"id": d["id"], "kind": "design", "label": d.get("title") or d["id"]})
    g = notes.get("gaps") or {}
    for it in g.get("gaps") or []:
        text = it.get("gap") if isinstance(it, dict) else str(it)
        if text:
            out.append({"id": None, "kind": "gap", "label": text[:300]})
    for text in g.get("research_directions") or []:
        out.append({"id": None, "kind": "direction", "label": str(text)[:300]})
    return out


# ---------------------------------------------------------------- planning
def draft_add_claim(ctx, text: str, claim_type: str, predicate: dict) -> dict:
    res = propose_claim(ctx, text, claim_type, predicate, _agent="draft")
    if res.get("claim_id") and res.get("status") == "pending":
        verify_claims(ctx, [res["claim_id"]])
        row = ctx.pg.execute("SELECT status, result FROM claims WHERE id=%s", (res["claim_id"],)).fetchone()
        res.update(status=row["status"], counted=_counted(row["result"]))
        res.pop("note", None)
    return res


DRAFT_ADD_CLAIM = Tool(
    "add_claim", "Count something the draft needs and record it as a claim, verified immediately, so the draft "
    "can cite it. Use test_claim first and write the text from the measured numbers. Predicate formats: "
    + PREDICATE_DOC + ".",
    obj({"text": STR, "claim_type": {"type": "string", "enum": ["prevalence", "trend"]},
         "predicate": {"type": "object"}}, ["text", "claim_type", "predicate"]), draft_add_claim)


def _outline_schema(keys: list[str]) -> dict:
    return obj({
        "title": {**STR, "description": "A specific working title"},
        "argument": {**STR, "description": "The central argument in 2-4 sentences, as the evidence supports it"},
        "sections": {"type": "array", "items": obj({
            "key": {"type": "string", "enum": keys},
            "points": {**STRS, "description": "2-6 short points for this section"},
            "claims": {**STRS, "description": "Claim ids (C12) that back the points"},
            "papers": {**STRS, "description": "Paper ids to cite in this section"}}, ["key", "points"])},
        "caveats": {**STRS, "description": "Where the evidence for the argument is thin or mixed"},
    }, ["title", "argument", "sections"])


PLANNER_SYSTEM = """You are the Draft Planner agent. A literature analysis has finished. The researcher wants a
{label} built on it, arguing for this direction:

{direction}

Your job is to gather the evidence the draft needs and return an outline. You do not write the draft.

How to work:
- Start with run_overview, and get_item for every item id the researcher named.
- Establish the gap with counts: use test_claim, then add_claim so the draft can cite the count (how many of
  the analysed papers do X, in which settings or years, with `where` for subgroups). Before calling anything
  rare or absent, run recheck_field. Aim for 3 to 8 new claims that carry the argument; do not re-count what an
  existing supported claim already says.
- Use research_vs_burden to show where research is thin relative to disease burden, results_table and
  method_comparison for what works, contradictions for open questions, and read_paper to confirm what key
  papers did before you plan to cite them for it.
- If the evidence does not support the direction (the "gap" is well covered, or rests on very few papers),
  say so in `argument` and `caveats` and reframe the direction honestly. Do not plan around claims that were
  not supported.
- In the outline, give every section its points and the claim ids and paper ids behind them. Use only ids the
  tools gave you.

Sections of this draft (keys): {sections}"""


@dataclass
class DraftPlanner(Agent):
    direction: str = ""
    about: list[str] = field(default_factory=list)

    def context_message(self, ctx, task: str) -> str:
        return (f"The run's research question: {ctx.question}\n\nDirection for the draft: {self.direction}\n"
                + (f"Items it builds on: {', '.join(self.about)}\n" if self.about else "") + f"\n{task}")


def _planner(kind: str, direction: str, about: list[str]) -> DraftPlanner:
    label, sections, last = KINDS[kind]
    keys = [s[0] for s in sections] + [last[0]]
    return DraftPlanner(
        name="draft_plan",
        role="Gathers the evidence for a draft and outlines it.",
        system=PLANNER_SYSTEM.format(label=label.lower(), direction=direction,
                                     sections=", ".join(f"{k} ({h})" for k, h, *_ in sections)),
        tools=[OVERVIEW_TOOL, ITEM_TOOL, READ_TOOL, TEST_TOOL, DRAFT_ADD_CLAIM, RECHECK_TOOL]
        + [t for t in ANALYSIS_TOOLS if t.name in ("value_counts", "cross_tab", "list_extractions")]
        + RESULT_TOOLS + [CITATION_INFO_TOOL, BURDEN_TOOL],
        finish_schema=_outline_schema(keys),
        max_turns=16, strong_model=True, long_output=True, direction=direction, about=about)


# ---------------------------------------------------------------- the evidence pack every section sees
PACK_CHARS = 60000
CARD_CHARS = 32000


def _card(r: dict) -> dict:
    d = r["data"]
    ev = d.get("evidence") or {}
    card = {"id": r["paper_id"], "title": (r["title"] or "")[:160], "year": r["year"], "corpus": r.get("corpus"),
            "read": r["source"]}
    for f in ("methods", "datasets", "data_modalities", "geography", "limitations"):
        if d.get(f):
            card[f] = d[f][:6]
    if d.get("validation_level") not in (None, "", "not_stated"):
        card["validation"] = d["validation_level"]
    if d.get("key_findings"):
        card["findings"] = str(d["key_findings"])[:260]
    res = [f"{x['metric']} {x['value']} ({x['model']})" for x in (d.get("reported_results") or [])[:3]]
    if res:
        card["results"] = res
    assoc = [f"{x['driver']}: {x['direction']}" for x in (d.get("reported_associations") or [])[:3]]
    if assoc:
        card["associations"] = assoc
    quote = next((q for f in ("methods", "data_modalities", "validation_level") for q in (ev.get(f) or [])), None)
    if quote:
        card["quote"] = quote[:200]
    return card


def _cards(ctx, first: list[str]) -> list[dict]:
    rows = {r["paper_id"]: r for r in _rows(ctx)}
    order = list(dict.fromkeys([p for p in first if p in rows] + [p for p in ctx.shortlist_ids() if p in rows]))
    out, used = [], 0
    for pid in order:
        c = _card(rows[pid])
        size = len(json.dumps(c, ensure_ascii=False))
        if used + size > CARD_CHARS:
            break
        out.append(c)
        used += size
    return out


def evidence_pack(ctx, kind: str, outline: dict, about: list[str], captions: list[str] | None = None) -> str:
    brief = get_brief(ctx)
    brief.pop("papers", None)            # the paper records below replace the bare title list
    notes = brief.pop("agent_outputs", {}) or {}
    pack = {"question": ctx.question, "run_facts": brief.pop("run_facts"), "claims": brief.pop("claims")}
    pack.update(brief)                   # reported performance, contradictions, citations
    try:
        from research_agent.tools.burden import research_vs_burden

        rb = research_vs_burden(ctx)
        if rb.get("countries"):
            pack["research_vs_burden"] = {"note": rb.get("note"), "countries": [
                {k: x[k] for k in ("country", "papers", "research_share", "burden_share", "ratio")}
                for x in rb["countries"][:15]]}
    except Exception:
        pass
    if about:
        pack["items_the_draft_builds_on"] = [get_item(ctx, i) for i in about]
    if kind == "review":
        from research_agent.tools.review import prisma_counts, protocol_markdown

        pack["review_record"] = {"prisma": prisma_counts(ctx), "protocol": protocol_markdown(ctx)[:6000]}
    if captions:
        pack["figures_and_tables"] = {"appended_by_code": captions,
                                      "note": "Refer to these by number; do not reproduce them."}
    outline_papers = [p for s in outline.get("sections", []) for p in s.get("papers") or []]
    pack["papers"] = _cards(ctx, outline_papers)
    text = json.dumps(pack, ensure_ascii=False, default=str)
    room = PACK_CHARS - len(text)
    if room > 2000 and notes:            # the agents' own notes, unverified, as background only
        pack["agent_notes_unverified"] = json.dumps(notes, ensure_ascii=False, default=str)[:room - 500]
        text = json.dumps(pack, ensure_ascii=False, default=str)
    return text


def _outline_text(outline: dict, sections) -> str:
    by_key = {s.get("key"): s for s in outline.get("sections") or [] if isinstance(s, dict)}
    lines = [f"Working title: {outline.get('title') or ''}", f"Central argument: {outline.get('argument') or ''}"]
    if outline.get("caveats"):
        lines.append("Caveats: " + "; ".join(outline["caveats"]))
    for key, heading, *_ in sections:
        s = by_key.get(key) or {}
        lines.append(f"\n[{key}] {heading}")
        lines += [f"- {p}" for p in s.get("points") or []]
        if s.get("claims"):
            lines.append("  claims: " + ", ".join(s["claims"]))
        if s.get("papers"):
            lines.append("  papers: " + ", ".join(s["papers"]))
    return "\n".join(lines)


# ---------------------------------------------------------------- writing
WRITER_SYSTEM = """You are the Draft writer. You write one section at a time of a {label} built on a finished,
evidence-checked literature analysis. The evidence pack, the outline and the sections written so far are in
the message; write only the section you are asked for.

WHO READS IT: {reader}. Write in a measured scientific register: flowing, argued prose, precise and hedged
where the evidence is thin, never breathless. Paragraphs, not bullet lists, unless the section asks for a list
or a table. Do not use em dashes; use commas, colons, semicolons or full stops.

Evidence rules (statements about the literature are checked by code after you write):
- Every quantitative statement about the literature comes from a SUPPORTED claim in the pack: quote its
  counted numbers (e.g. "31 of 58 studies") and cite it as [C12]. Mention unsupported claims only as not
  supported, without brackets ("claim C42, not supported"); never use numbers from rejected claims.
- Counts about the review itself (papers analysed, read in full, PRISMA stages) come from run_facts or the
  review record. Numbers in agent_notes_unverified are not verified: describe them in words.
- Never add counts together, and never turn a count into a larger claim than it is.
- Cite papers as [arXiv:2401.00001] or [PMC1234567], only ids from the pack, and only for what their record
  shows. Plain square brackets.
- Say which findings rest on preprints (arXiv) and which on published articles (PMC) when it matters.
{plan_rules}"""

PLAN_RULES = """
Sections marked PLAN are the applicant's proposal, not findings:
- Write them as intentions in the future tense ("We will...").
- Cite papers only to justify a choice (a dataset they used, a validation design that worked).
- Never invent sample sizes, sites, partners, costs or results. Where the applicant must decide something,
  write a placeholder in square brackets starting with "to be confirmed", e.g. [to be confirmed: number of
  districts]."""

READERS = {"proposal": "a funding panel and peer reviewers: scientists from this and adjacent fields",
           "review": "journal reviewers and readers: researchers and practitioners in global health and data science"}


def _clean(text: str, heading: str) -> str:
    text = (text or "").strip()
    text = re.sub(r"^\s*#{1,3}\s+.*\n+", "", text) if re.match(r"^\s*#{1,3}\s", text) else text  # own heading
    text = re.sub(r"\s*—\s*", ", ", text)                    # em dashes (year ranges like 2015–2020 stay)
    text = re.sub(r"\s+–\s+", ", ", text)                    # spaced en dashes used as em dashes
    return text.strip()


def _trim_cut(text: str) -> str:
    """A section cut off by the output limit keeps its finished paragraphs."""
    parts = text.rstrip().split("\n\n")
    return "\n\n".join(parts[:-1]) if len(parts) > 1 else text


def _write(llm, system: str, pack: str, outline: str, written: list[tuple[str, str]], sec: tuple) -> str:
    key, heading, role, guidance, words = sec
    blocks = [{"type": "text", "text": "EVIDENCE PACK (JSON):\n" + pack},
              {"type": "text", "text": "OUTLINE:\n" + outline}]
    if written:
        blocks.append({"type": "text", "text": "SECTIONS WRITTEN SO FAR:\n\n"
                       + "\n\n".join(f"## {h}\n\n{t}" for h, t in written)})
    kind = {"plan": "PLAN (the applicant's proposal)", "record": "RECORD (how the review was done)",
            "evidence": "EVIDENCE (statements about the literature)"}[role]
    blocks.append({"type": "text", "text": (
        f"Write the section \"{heading}\" [{key}], a {kind} section, now. {guidance} About {words} words. "
        "Follow the outline's points for this section and cite what backs them. Start directly with the text: "
        "no heading for the section itself, and no closing remarks about the draft.")})
    resp = llm.chat(system, [{"role": "user", "content": blocks}], max_tokens=min(
        settings.long_output_max_tokens, max(1200, int(words * 3))))
    text = resp.text or ""
    if (resp.stop_reason or "").lower() in ("length", "max_tokens"):
        text = _trim_cut(text)
    return _clean(text, heading)


# ---------------------------------------------------------------- assembling and checking
def _references(ctx, cited: list[str]) -> list[str]:
    papers = {r["paper_id"]: r for r in ctx.pg.execute(
        "SELECT paper_id, source, title, year, authors, doi FROM papers WHERE paper_id = ANY(%s)",
        (cited or [""],)).fetchall()}
    lines = []
    for pid in cited:
        p = papers.get(pid)
        if not p:
            continue
        names = [a.strip() for a in re.split(r",|\band\b", p["authors"] or "") if a.strip()]
        who = (_clean_author(names[0]) if names else "Unknown") + (" et al." if len(names) > 1 else "")
        url = (f"https://pmc.ncbi.nlm.nih.gov/articles/{pid}/" if p["source"] == "pmc"
               else f"https://arxiv.org/abs/{pid}")
        label = pid if p["source"] == "pmc" else f"arXiv:{pid}"
        lines.append(f"- **{label}**: {who} ({p['year']}). {p['title']}. {url}"
                     + (" (preprint)" if p["source"] != "pmc" else ""))
    return lines


def _evidence_table(ctx, body: str) -> list[str]:
    ids = sorted({int(c) for c in _CITE_CLAIM.findall(body)})
    if not ids:
        return []
    rows = ctx.pg.execute("SELECT id, text, status, result FROM claims WHERE run_id=%s AND id = ANY(%s) ORDER BY id",
                          (ctx.run_id, ids)).fetchall()
    lines = ["## Evidence behind the numbers", "",
             "Each [C] citation above is a count made by code over the papers analysed.", "",
             "| Claim | Statement | Verdict | Counted |", "|---|---|---|---|"]
    for c in rows:
        lines.append(f"| C{c['id']} | {c['text'].replace('|', '/')} | {c['status']} | {_counted(c['result']) or ''} |")
    return lines + [""]


def _figures(ctx, kind: str) -> tuple[list[str], list[str]]:
    """Code-made figures and tables, numbered: (Markdown lines, captions). The review gets the PRISMA flow as
    Figure 1. The captions go into the evidence pack so the text can refer to them by number."""
    out, captions, n = [], [], 0

    def add(block: list[str], label: str) -> None:
        caption = f"{label}. {block[0][3:].replace(' (computed)', '')}"
        captions.append(caption)
        out.extend([f"## {caption}"] + block[1:])

    for kind_ok, module, fn in ((kind == "review", "research_agent.tools.review", "prisma_markdown"),
                                (True, "research_agent.tools.results", "results_markdown"),
                                (True, "research_agent.tools.burden", "burden_markdown")):
        if not kind_ok:
            continue
        try:
            import importlib

            lines = getattr(importlib.import_module(module), fn)(ctx)
        except Exception:
            continue
        starts = [i for i, line in enumerate(lines) if line.startswith("## ")] + [len(lines)]
        for a, b in zip(starts, starts[1:]):
            if fn == "prisma_markdown":
                add(["## Study selection (PRISMA 2020)"] + lines[a + 1:b], "Figure 1")
            else:
                n += 1
                add(lines[a:b], f"Table {n}")
    return out, captions


def write_draft(ctx, kind: str, direction: str, about: list[str] | None = None) -> dict:
    """Plan, write and check one draft. Returns {title, content_md, meta}."""
    if kind not in KINDS:
        raise ValueError(f"kind must be one of {', '.join(KINDS)}")
    about = [a.strip().upper() for a in about or [] if a.strip()]
    label, sections, last = KINDS[kind]
    direction = direction.strip() or ("the main gap the analysis found" if kind == "proposal"
                                      else "a review answering the run's question")
    before = {r["id"] for r in ctx.pg.execute("SELECT id FROM claims WHERE run_id=%s", (ctx.run_id,)).fetchall()}

    outline = _planner(kind, direction, about).run(ctx, "Gather the evidence and return the outline.")
    if not outline.get("sections"):
        outline = {"title": outline.get("title") or label, "argument": outline.get("argument") or direction,
                   "sections": [], "caveats": outline.get("caveats") or []}
    verify_claims(ctx)                                   # anything still pending is checked before writing
    figures, captions = _figures(ctx, kind)
    pack = evidence_pack(ctx, kind, outline, about, captions)
    outline_txt = _outline_text(outline, sections + [last])
    system = WRITER_SYSTEM.format(label=label.lower(), reader=READERS[kind],
                                  plan_rules=PLAN_RULES if kind == "proposal" else "")
    llm = ctx.llm_factory(strong=True, step="draft")
    setattr(llm, "_step", "draft")
    written: list[tuple[str, str]] = []
    for sec in sections:
        ctx.emit("draft", "message", {"text": f"writing {sec[1]}"})
        text = _write(llm, system, pack, outline_txt, written, sec)
        if kind == "review" and sec[0] == "methods":
            text = text + "\n\n" + AUTOMATION_NOTE
        written.append((sec[1], text))
    opening = _write(llm, system, pack, outline_txt, written, last)

    parts = [(last[1], opening)] + written
    body = "\n\n".join(f"## {h}\n\n{t}" for h, t in parts)
    number_check = None
    if settings.number_check:
        try:
            from research_agent.agents.number_check import resolve_numbers

            body, number_check = resolve_numbers(ctx, body)
        except Exception as exc:   # the check improves a draft; it must never lose one
            ctx.emit("number_check", "error", {"error": str(exc)[:300]})
    body, audit = audit_answer(ctx, body)

    shortlist = set(ctx.shortlist_ids())
    cited = [p for p in dict.fromkeys(_cited_ids(body)) if p in shortlist]
    facts = run_facts(ctx)
    title = (outline.get("title") or label).strip().strip("#").strip()
    date = datetime.now(timezone.utc).strftime("%d %B %Y")
    notice = (f"*{label}, draft of {date}. Built from an analysis of {facts['shortlist']} papers "
              f"({facts['fulltext']} read in full) for the question: \"{ctx.question}\". Statements about the "
              "literature were checked against those papers: citations to other papers were removed and numbers "
              "no count supports are marked [unverified].")
    if kind == "proposal":
        notice += (" Aims, methods, outcomes, risks and the workplan are the applicant's proposal, not findings; "
                   "items in square brackets starting \"to be confirmed\" are for the applicant to decide.*")
    else:
        notice += " Screening and extraction were automated; see the note in Methods.*"
    tail = (["## Budget", "", "_To be completed by the applicant._", ""] if kind == "proposal" else
            ["## Declarations", "", "_Author contributions, funding, competing interests and data availability: "
             "to be completed by the authors._", ""])
    content = "\n".join([f"# {title}", "", notice, "", body.strip(), "", *tail, *figures,
                         *_evidence_table(ctx, body), f"## References ({len(cited)})", "",
                         *_references(ctx, cited)]) + "\n"
    new_claims = sorted(r["id"] for r in ctx.pg.execute("SELECT id FROM claims WHERE run_id=%s",
                                                        (ctx.run_id,)).fetchall() if r["id"] not in before)
    meta = {"audit": audit, "number_check": {k: v for k, v in (number_check or {}).items() if k != "log"},
            "cited_papers": cited, "new_claims": [f"C{c}" for c in new_claims],
            "argument": outline.get("argument"), "caveats": outline.get("caveats") or []}
    return {"title": title, "content_md": content, "meta": meta}


# ---------------------------------------------------------------- storing and running
def start(run_id: str, kind: str, direction: str, about: list[str] | None = None) -> int:
    _ensure_schema()
    if kind not in KINDS:
        raise ValueError(f"kind must be one of {', '.join(KINDS)}")
    conn = connect()
    try:
        run = conn.execute("SELECT status FROM runs WHERE run_id=%s", (run_id,)).fetchone()
        if not run:
            raise ValueError(f"No run with id {run_id}")
        return conn.execute("INSERT INTO drafts (run_id, kind, direction, about) VALUES (%s,%s,%s,%s) RETURNING id",
                            (run_id, kind, direction or "", about or None)).fetchone()["id"]
    finally:
        conn.close()


def run_draft(draft_id: int, provider: str | None = None, llm_factory=None) -> dict:
    """Write a stored draft request. Never changes the run's report."""
    _ensure_schema()
    conn = connect()
    try:
        d = conn.execute("SELECT id, run_id, kind, direction, about FROM drafts WHERE id=%s", (draft_id,)).fetchone()
        if not d:
            raise ValueError(f"No draft {draft_id}")
        conn.execute("UPDATE drafts SET status='running' WHERE id=%s", (draft_id,))
    finally:
        conn.close()
    ctx = RunContext.attach(str(d["run_id"]), provider=provider, llm_factory=llm_factory)
    try:
        out = write_draft(ctx, d["kind"], d["direction"], d["about"] or [])
        ctx.pg.execute("UPDATE drafts SET status='done', title=%s, content_md=%s, meta=%s::jsonb, finished_at=now() "
                       "WHERE id=%s", (out["title"], out["content_md"], json.dumps(out["meta"], default=str), draft_id))
        return {"id": draft_id, **out}
    except Exception as exc:
        ctx.pg.execute("UPDATE drafts SET status='failed', content_md=%s, finished_at=now() WHERE id=%s",
                       (f"The draft failed: {str(exc)[:300]}", draft_id))
        raise
    finally:
        ctx.close()


def draft_in_background(run_id: str, kind: str, direction: str, about: list[str] | None = None,
                        provider: str | None = None) -> dict:
    from research_agent.jobs import enqueue

    did = start(run_id, kind, direction, about)
    job = enqueue("draft", {"draft_id": did, "provider": provider})
    return {"draft_id": did, "job_id": job}


def list_drafts(run_id: str) -> list[dict]:
    _ensure_schema()
    conn = connect()
    try:
        return conn.execute("SELECT id, kind, direction, about, status, title, created_at, finished_at FROM drafts "
                            "WHERE run_id=%s ORDER BY id DESC", (run_id,)).fetchall()
    finally:
        conn.close()


def get_draft(draft_id: int) -> dict | None:
    _ensure_schema()
    conn = connect()
    try:
        return conn.execute("SELECT id, run_id, kind, direction, about, status, title, content_md, meta, created_at, "
                            "finished_at FROM drafts WHERE id=%s", (draft_id,)).fetchone()
    finally:
        conn.close()
