"""Report inputs for the Synthesis agent, and deterministic post-processing of its output.

The references list and evidence table are generated by code, never by the LLM, and every citation
in the body is checked against the run's shortlist and claim table."""
from __future__ import annotations

import re

from research_agent.tools.base import Tool, obj
from research_agent.tools.extraction import extraction_coverage

_CITE_PAPER = re.compile(r"\[arXiv:([^\]\s]+)\]")
_CITE_CLAIM = re.compile(r"\[C(\d+)\]")


def get_brief(ctx) -> dict:
    claims = ctx.pg.execute(
        "SELECT id, agent, text, claim_type, status, result, review_note FROM claims WHERE run_id=%s ORDER BY id",
        (ctx.run_id,)).fetchall()
    compact = []
    for c in claims:
        r = c["result"] or {}
        entry = {"claim": f"C{c['id']}", "agent": c["agent"], "text": c["text"], "status": c["status"]}
        if c["claim_type"] == "prevalence" and r:
            entry["numbers"] = f"{r.get('n_matching')} of {r.get('denominator')} papers ({r.get('share')})"
            if r.get("caveat"):
                entry["caveat"] = r["caveat"]
        elif r:
            entry["numbers"] = r.get("window")
        if c["review_note"]:
            entry["review_note"] = c["review_note"][:300]
        compact.append(entry)
    papers = ctx.pg.execute(
        """SELECT p.paper_id, p.title, p.year FROM run_papers rp JOIN papers p USING (paper_id)
           WHERE rp.run_id=%s ORDER BY p.year DESC""", (ctx.run_id,)).fetchall()
    notes = {k: v for k, v in ctx.notes().items() if k not in ("synthesis", "orchestrator")}
    return {"question": ctx.question, "coverage": extraction_coverage(ctx), "agent_outputs": notes,
            "claims": compact, "papers": papers}


REPORT_TOOLS = [Tool("get_brief", "Everything you need: agent outputs, claims with verdicts and numbers, "
                     "and the shortlist (ids, titles, years).", obj({}), get_brief)]


def finalize_report(ctx, body: str) -> tuple[str, dict]:
    """Validate citations, then append a code-generated evidence table and reference list."""
    shortlist = set(ctx.shortlist_ids())
    claims = {c["id"]: c for c in ctx.pg.execute(
        "SELECT id, text, status, claim_type, result FROM claims WHERE run_id=%s ORDER BY id",
        (ctx.run_id,)).fetchall()}

    bad_papers = sorted({pid for pid in _CITE_PAPER.findall(body) if pid not in shortlist})
    bad_claims = sorted({int(cid) for cid in _CITE_CLAIM.findall(body)
                         if int(cid) not in claims or claims[int(cid)]["status"] != "supported"})
    for pid in bad_papers:
        body = body.replace(f"[arXiv:{pid}]", "[citation removed: not in analysed set]")
    for cid in bad_claims:
        body = body.replace(f"[C{cid}]", f"[C{cid} — not verified]")

    cited = [pid for pid in dict.fromkeys(_CITE_PAPER.findall(body)) if pid in shortlist]
    papers = {r["paper_id"]: r for r in ctx.pg.execute(
        "SELECT paper_id, title, year, authors FROM papers WHERE paper_id = ANY(%s)",
        (list(shortlist),)).fetchall()}

    lines = [body.strip(), "", "## Evidence table", "",
             "| Claim | Statement | Verdict | Evidence |", "|---|---|---|---|"]
    for cid, c in claims.items():
        r = c["result"] or {}
        if c["claim_type"] == "prevalence" and r:
            ev = f"{r.get('n_matching')}/{r.get('denominator')} papers ({round(100 * (r.get('share') or 0))}%)"
        elif r:
            w = r.get("window", {})
            ev = (f"{w.get('early_mean')} → {w.get('late_mean')} per 10k arXiv papers "
                  f"(×{w.get('ratio_late_over_early')})")
        else:
            ev = "—"
        text = c["text"].replace("|", "/")
        lines.append(f"| C{cid} | {text} | {c['status']} | {ev} |")

    lines += ["", f"## References ({len(shortlist)} papers analysed)", ""]
    ordered = cited + sorted(set(shortlist) - set(cited), key=lambda p: (-(papers.get(p, {}).get('year') or 0), p))
    for pid in ordered:
        p = papers.get(pid)
        if p:
            authors = (p["authors"] or "").split(",")[0].strip()
            etal = " et al." if "," in (p["authors"] or "") or " and " in (p["authors"] or "") else ""
            lines.append(f"- **arXiv:{pid}** — {p['title']} ({authors}{etal}, {p['year']}). "
                         f"https://arxiv.org/abs/{pid}")
    audit = {"removed_paper_citations": bad_papers, "flagged_claim_citations": bad_claims,
             "papers_cited": len(cited)}
    return "\n".join(lines), audit
