"""Report inputs for the Synthesis agent, and deterministic post-processing of its output.

The references list and evidence table are generated by code, never by the LLM, and every citation
in the body is checked against the run's shortlist and claim table."""
from __future__ import annotations

import json
import re

from research_agent.config import settings
from research_agent.tools.base import Tool, obj
from research_agent.tools.extraction import extraction_coverage

# Papers are cited as [arXiv:2401.00001] or [PMC1234567]; group 1 is the id either way.
_CITE_PAPER = re.compile(r"\[(?:arXiv:([^\]\s]+)|(PMC\d+))\]")


def _cited_ids(body: str) -> list[str]:
    return [a or b for a, b in _CITE_PAPER.findall(body)]


def _cite(pid: str) -> str:
    return f"[{pid}]" if pid.startswith("PMC") else f"[arXiv:{pid}]"
_CITE_CLAIM = re.compile(r"\[C(\d+)\]")


BRIEF_CHARS = max(9000, settings.context_budget_chars // 2)


def get_brief(ctx) -> dict:
    """Claims come first and are never cut: the report may only cite them. Agent notes get what space is left."""
    claims = ctx.pg.execute(
        "SELECT id, agent, text, claim_type, status, result, review_note FROM claims WHERE run_id=%s ORDER BY id",
        (ctx.run_id,)).fetchall()
    compact = []
    for c in claims:
        r = c["result"] or {}
        entry = {"claim": f"C{c['id']}", "status": c["status"], "text": c["text"][:220]}
        if c["claim_type"] == "prevalence" and r:
            entry["numbers"] = f"{r.get('n_matching')} of {r.get('denominator')} papers"
            if r.get("wording_problem"):
                entry["why_not_supported"] = r["wording_problem"][:200]
        elif r:
            entry["numbers"] = r.get("window")
        if c["review_note"] and c["status"] != "supported":
            entry["review_note"] = c["review_note"][:200]
        compact.append(entry)
    papers = [{"paper_id": r["paper_id"], "title": r["title"][:80]} for r in ctx.pg.execute(
        """SELECT p.paper_id, p.title, p.year FROM run_papers rp JOIN papers p USING (paper_id)
           WHERE rp.run_id=%s ORDER BY p.year DESC""", (ctx.run_id,)).fetchall()]
    facts = run_facts(ctx)
    out = {"question": ctx.question,
           "run_facts": {**facts, "note": "years = shortlist years; corpus_years = whole corpus"},
           "claims": compact, "papers": papers}
    notes_src = {k: v for k, v in ctx.notes().items() if k not in ("synthesis", "orchestrator")}
    room = BRIEF_CHARS - len(json.dumps(out, default=str, ensure_ascii=False)) - 200
    per_note = max(300, room // max(1, len(notes_src)))
    notes = {}
    for k, v in notes_src.items():
        text = json.dumps(v, ensure_ascii=False, default=str)
        notes[k] = v if len(text) <= per_note else text[:per_note] + "…"
    out["agent_outputs"] = notes
    return out


REPORT_TOOLS = [Tool("get_brief", "Everything you need: every claim (its id is the `claim` field), verdict and numbers, run facts, "
                     "the shortlist (ids, titles), and agent outputs.", obj({}), get_brief,
                     max_chars=BRIEF_CHARS)]


_N_OF_M = re.compile(r"\b(\d{1,3}(?:,\d{3})+|\d{1,6})\s*(?:of|/|out of)\s*(\d{1,3}(?:,\d{3})+|\d{1,6})"
                     r"(?![\d,]*\d)(?!\s*\[unverified)")


def _int(x: str) -> int:
    return int(x.replace(",", ""))


_SENTENCE = re.compile(r"(?<=[.!?])\s+(?=[A-Z*\[(_])|\n+")


def _pair(c) -> tuple[int, int] | None:
    r = c.get("result") or {}
    if c.get("claim_type") != "prevalence" or r.get("denominator") is None:
        return None
    return int(r.get("n_matching") or 0), int(r["denominator"])


def _pairs_of(c) -> set[tuple[int, int]]:
    """A claim backs both its count and its complement: 14 of 46 named a dataset means 32 of 46 did not."""
    p = _pair(c)
    return {p, (p[1] - p[0], p[1])} if p else set()


def align_claim_citations(body: str, claims: dict) -> tuple[str, list[str]]:
    """Check each [Cn] against the "n of N" numbers in its own sentence.

    Models sometimes cite the right number with the wrong claim id. When the sentence's number belongs to
    exactly one other supported claim, the citation is corrected; when no claim backs it, the citation is
    marked as a mismatch. Sentences without numbers are left alone."""
    fixes: list[str] = []
    supported = {cid: _pair(c) for cid, c in claims.items() if c["status"] == "supported" and _pair(c)}
    # a complement number ("32 of 46 did not") maps back to the claim that counted the 14

    def fix_sentence(sent: str) -> str:
        cited = [int(x) for x in _CITE_CLAIM.findall(sent)]
        pairs = {(_int(a), _int(b)) for a, b in _N_OF_M.findall(sent)}
        if not cited or not pairs:
            return sent
        covered = {q for c in cited if c in claims for q in _pairs_of(claims[c]) & pairs}
        uncovered = pairs - covered
        for cid in dict.fromkeys(cited):
            if cid not in claims or _pairs_of(claims[cid]) & pairs or not _pairs_of(claims[cid]) or not uncovered:
                continue
            candidates = [k for k, v in supported.items() if v in uncovered and k not in cited]
            if len(candidates) > 1:  # same numbers in several claims: prefer the one whose wording fits
                words = set(re.findall(r"[a-z]{4,}", sent.lower()))
                score = {k: len(words & set(re.findall(r"[a-z]{4,}", claims[k]["text"].lower())))
                         for k in candidates}
                best = max(score.values())
                if list(score.values()).count(best) == 1:
                    candidates = [k for k in candidates if score[k] == best]
            if len(candidates) == 1:
                new = candidates[0]
                sent = sent.replace(f"[C{cid}]", f"[C{new}]")
                uncovered.discard(supported[new])
                fixes.append(f"C{cid}->C{new}")
            elif not candidates and uncovered <= {
                    q for k in map(int, re.findall(r"\bC(\d+)\b", sent))
                    if k in claims and claims[k]["status"] != "rejected" for q in _pairs_of(claims[k])}:
                continue   # the other number belongs to a claim named in this sentence ("claim C166, unsupported")
            else:
                sent = sent.replace(f"[C{cid}]", f"[C{cid} — number does not match this claim]")
                fixes.append(f"C{cid}: mismatch")
        return sent

    out, last = [], 0
    for m in _SENTENCE.finditer(body):
        out.append(fix_sentence(body[last:m.start()]))
        out.append(m.group(0))
        last = m.end()
    out.append(fix_sentence(body[last:]))
    return "".join(out), fixes


def _clean_author(name: str) -> str:
    """arXiv author strings carry LaTeX accents (Jos\\'e, Yaz{\\i}c{\\i}) and affiliation marks ((1))."""
    name = re.sub(r"\(\d+(?:,\s*\d+)*\)", "", name)
    if "\\" in name or "{" in name:
        try:
            from pylatexenc.latex2text import LatexNodes2Text

            name = LatexNodes2Text().latex_to_text(name)
        except Exception:
            name = re.sub(r"[\\{}]", "", name)
    return " ".join(name.split())


def normalise_citations(body: str) -> str:
    """Some models write citations with other bracket styles (e.g. 【C3】 or ［arXiv:…］). Convert
    them to [..] so the checks below see every citation."""
    body = re.sub(r"[【［〔]\s*(C\d+|PMC\d+|arXiv:[^】］〕\s]+)\s*[】］〕]", r"[\1]", body)
    body = re.sub(r"\[arXiv:(PMC\d+)\]", r"[\1]", body)  # a PMC id written in arXiv form
    return re.sub(r"\[\s*(C\d+)\s*,\s*(C\d+)\s*\]", r"[\1] [\2]", body)


def run_facts(ctx) -> dict:
    """Facts about the run computed by code, so the report never has to take the LLM's word for them."""
    cov = extraction_coverage(ctx)
    years = ctx.pg.execute(
        """SELECT min(p.year) lo, max(p.year) hi FROM run_papers rp JOIN papers p USING (paper_id)
           WHERE rp.run_id=%s""", (ctx.run_id,)).fetchone()
    corpus = ctx.pg.execute("SELECT count(*) n, min(year) lo, max(year) hi FROM papers").fetchone()
    shortlist_mix = {r["source"]: r["n"] for r in ctx.pg.execute(
        """SELECT p.source, count(*) n FROM run_papers rp JOIN papers p USING (paper_id)
           WHERE rp.run_id=%s GROUP BY p.source""", (ctx.run_id,)).fetchall()}
    corpus_mix = {r["source"]: r["n"] for r in ctx.pg.execute(
        "SELECT source, count(*) n FROM papers GROUP BY source").fetchall()}
    return {"shortlist": cov["shortlist_size"], "extracted": cov["extracted"],
            "fulltext": cov["by_source"].get("fulltext", 0), "abstract_only": cov["by_source"].get("abstract", 0),
            "years": (years["lo"], years["hi"]), "corpus": corpus["n"], "corpus_years": (corpus["lo"], corpus["hi"]),
            "shortlist_by_corpus": shortlist_mix, "corpus_by_source": corpus_mix}


def audit_numbers(body: str, allowed: set[tuple[int, int]]) -> tuple[str, int]:
    """Mark every "n of N" in the text that no verified claim or run fact backs up."""
    flagged = 0

    def repl(m):
        nonlocal flagged
        if (_int(m.group(1)), _int(m.group(2))) in allowed:
            return m.group(0)
        flagged += 1
        return m.group(0) + " [unverified]"

    return _N_OF_M.sub(repl, body), flagged


def finalize_report(ctx, body: str) -> tuple[str, dict]:
    """Validate citations and numbers, then append code-generated run facts, evidence table and references."""
    body = normalise_citations(body)
    shortlist = set(ctx.shortlist_ids())
    claims = {c["id"]: c for c in ctx.pg.execute(
        "SELECT id, text, status, claim_type, result FROM claims WHERE run_id=%s ORDER BY id",
        (ctx.run_id,)).fetchall()}
    facts = run_facts(ctx)
    allowed = {(facts["fulltext"], facts["shortlist"]), (facts["abstract_only"], facts["shortlist"]),
               (facts["extracted"], facts["shortlist"]), (facts["fulltext"], facts["extracted"]),
               (facts["abstract_only"], facts["extracted"])}
    for c in claims.values():
        r = c["result"] or {}
        # Supported claims back their count. So do unsupported ones: their count was computed by code, only
        # the claim's threshold failed. Rejected claims do not (their predicate itself was judged wrong).
        if c["status"] in ("supported", "unsupported") and r.get("denominator") is not None:
            n, d = int(r.get("n_matching") or 0), int(r["denominator"])
            allowed |= {(n, d), (d - n, d)}  # "4 of 60 state it" also backs "56 of 60 are silent"
    statuses = [c["status"] for c in claims.values()]
    for st in ("supported", "rejected", "unsupported"):
        allowed.add((statuses.count(st), len(statuses)))
    for e in ctx.pg.execute("SELECT payload FROM run_events WHERE run_id=%s AND kind='count'",
                            (ctx.run_id,)).fetchall():
        allowed.add((int(e["payload"]["n"]), int(e["payload"]["total"])))  # corpus_count results

    body, citation_fixes = align_claim_citations(body, claims)
    bad_papers = sorted({pid for pid in _cited_ids(body) if pid not in shortlist})
    bad_claims = sorted({int(cid) for cid in _CITE_CLAIM.findall(body)
                         if int(cid) not in claims or claims[int(cid)]["status"] != "supported"})
    for pid in bad_papers:
        body = body.replace(_cite(pid), "[citation removed: not in analysed set]")
    for cid in bad_claims:
        body = body.replace(f"[C{cid}]", f"[C{cid} — not verified]")

    body, unverified_numbers = audit_numbers(body, allowed)
    cited = [pid for pid in dict.fromkeys(_cited_ids(body)) if pid in shortlist]
    papers = {r["paper_id"]: r for r in ctx.pg.execute(
        "SELECT paper_id, source, title, year, authors, license FROM papers WHERE paper_id = ANY(%s)",
        (list(shortlist),)).fetchall()}

    lo, hi = facts["years"]
    lines = [body.strip(), "", "## Run facts (computed by code)", "",
             f"- Papers analysed: {facts['shortlist']} "
             f"(read in full: {facts['fulltext']}, abstract only: {facts['abstract_only']})",
             f"- Publication years of analysed papers: {lo}–{hi}" if lo else "- Publication years: n/a",
             f"- Corpus searched: {facts['corpus']:,} health papers ({facts['corpus_years'][0]}–"
             f"{facts['corpus_years'][1]}): " + ", ".join(f"{n:,} {src}" for src, n in
                                                          sorted(facts["corpus_by_source"].items())),
             "- Papers analysed by corpus: " + (", ".join(f"{n} {src}" for src, n in
                                                          sorted(facts["shortlist_by_corpus"].items())) or "n/a"),
             f"- Numbers marked [unverified] in the text above: {unverified_numbers} "
             "(not backed by a supported claim or these facts)",
             "", "## Evidence table", "",
             "| Claim | Statement | Verdict | Evidence |", "|---|---|---|---|"]
    for cid, c in claims.items():
        r = c["result"] or {}
        if c["claim_type"] == "prevalence" and r:
            ev = f"{r.get('n_matching')}/{r.get('denominator')} papers ({round(100 * (r.get('share') or 0))}%)"
        elif r:
            w = r.get("window", {})
            unit = {"arxiv": "arXiv", "pmc": "PMC", "all": "all"}.get(r.get("source") or "arxiv", "arXiv")
            if r.get("within"):
                ev = (f"{w.get('early_mean')}% → {w.get('late_mean')}% of '{r['within']}' papers ({unit}) "
                      f"(×{w.get('ratio_late_over_early')})")
            else:
                ev = (f"{w.get('early_mean')} → {w.get('late_mean')} per 10k {unit} papers "
                      f"(×{w.get('ratio_late_over_early')})")
        else:
            ev = "—"
        text = c["text"].replace("|", "/")
        lines.append(f"| C{cid} | {text} | {c['status']} | {ev} |")

    lines += ["", f"## References ({len(shortlist)} papers analysed)", ""]
    ordered = cited + sorted(set(shortlist) - set(cited), key=lambda p: (-(papers.get(p, {}).get('year') or 0), p))
    for pid in ordered:
        p = papers.get(pid)
        if p:
            names = [a.strip() for a in re.split(r",|\band\b", p["authors"] or "") if a.strip()]
            authors = _clean_author(names[0]) if names else "Unknown"
            etal = " et al." if len(names) > 1 else ""
            if p.get("source") == "pmc":
                from research_agent.ingestion.pmc import licence_is_noncommercial

                nc = " *(licence: non-commercial)*" if licence_is_noncommercial(p.get("license") or "") else ""
                lines.append(f"- **{pid}** — {p['title']} ({authors}{etal}, {p['year']}). "
                             f"https://pmc.ncbi.nlm.nih.gov/articles/{pid}/{nc}")
            else:
                lines.append(f"- **arXiv:{pid}** — {p['title']} ({authors}{etal}, {p['year']}). "
                             f"https://arxiv.org/abs/{pid}")
    audit = {"removed_paper_citations": bad_papers, "flagged_claim_citations": bad_claims,
             "papers_cited": len(cited), "unverified_numbers": unverified_numbers,
             "claim_citation_fixes": citation_fixes}
    return "\n".join(lines), audit
